"""Recreate all tables

Revision ID: 04aaa7a8bf76
Revises: None
Create Date: 2025-03-13 17:28:45.561294

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '04aaa7a8bf76'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
                    sa.Column('category_name', sa.String()),
                    sa.PrimaryKeyConstraint('category_name')
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer()),
                    sa.Column('name', sa.String()),
                    sa.Column('email', sa.String()),
                    sa.Column('hashed_password', sa.String()),
                    sa.Column('delivery_address', sa.String()),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('orders',
                    sa.Column('order_id', sa.Integer()),
                    sa.Column('user_id', sa.Integer()),
                    sa.Column('created_at', sa.Date()),
                    sa.Column('status', sa.String()),
                    sa.Column('delivery_address', sa.String()),
                    sa.Column('order_items', sa.JSON()),
                    sa.Column('total_cost', sa.Integer()),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('order_id')
                    )
    op.create_table('products',
                    sa.Column('product_id', sa.Integer()),
                    sa.Column('name', sa.String()),
                    sa.Column('description', sa.String()),
                    sa.Column('price', sa.Integer()),
                    sa.Column('product_quantity', sa.Integer()),
                    sa.Column('image', sa.Integer()),
                    sa.Column('features', sa.JSON()),
                    sa.Column('category_name', sa.String()),
                    sa.ForeignKeyConstraint(['category_name'], ['categories.category_name'], ),
                    sa.PrimaryKeyConstraint('product_id')
                    )
    op.create_table('reviews',
                    sa.Column('review_id', sa.Integer()),
                    sa.Column('user_id', sa.Integer()),
                    sa.Column('product_id', sa.Integer()),
                    sa.Column('feedback', sa.String()),
                    sa.Column('rating', sa.Integer()),
                    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('review_id')
                    )
    op.create_table('shopping_carts',
                    sa.Column('cart_id', sa.Integer()),
                    sa.Column('user_id', sa.Integer()),
                    sa.Column('product_id', sa.Integer()),
                    sa.Column('quantity', sa.Integer()),
                    sa.Column('total_cost', sa.Integer()),
                    sa.ForeignKeyConstraint(['product_id'], ['products.product_id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('cart_id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shopping_carts')
    op.drop_table('reviews')
    op.drop_table('products')
    op.drop_table('orders')
    op.drop_table('users')
    op.drop_table('categories')
    ### end Alembic commands ###
