"""add_balance_to_users

Revision ID: 92d746c37098
Revises: 5f8c49130302
Create Date: 2025-10-24 20:42:48.877783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92d746c37098'
down_revision: Union[str, None] = '5f8c49130302'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('balance', sa.Integer(), server_default='0', nullable=False))
    op.create_check_constraint('check_balance_non_negative', 'users', 'balance >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('check_balance_non_negative', 'users', type_='check')
    op.drop_column('users', 'balance')
    # ### end Alembic commands ###
