"""Initial migration

Revision ID: 832f29662ee2
Revises: 
Create Date: 2026-01-01 17:55:53.237961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '832f29662ee2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('delivery_address', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('balance', sa.Integer(), server_default='0', nullable=False),
    sa.CheckConstraint('balance >= 0', name='check_balance_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###

